# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'annotationTool' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for annotationTool
  
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftCSV'

end

target 'hotPointTool' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hotPointTool

  target 'hotPointToolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hotPointToolUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
